# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: word-replace-api-svc
spec:
  selector:
    app: word-replace-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# word-replace-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-replace-api
  labels:
    app: word-replace-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-replace-api
  template:
    metadata:
      labels:
        app: word-replace-api
    spec:
      containers:
        - name: word-replace-api
          image: word-replace:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
