apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: word-replace-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: word-replace-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
